version: "2.27.1-desktop.1"
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3304:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  healthcheck:
    image: alpine:latest
    depends_on:
      mysql:
        condition: service_healthy
    command: ["sh", "-c", "echo 'MySQL is healthy.' && exit 0 || exit 1"]

  adminer:
    image: adminer
    restart: always
    ports:
      - "8091:8080"

volumes:
  mysql:
